### ISSUE TITLE
Led blinking

### ISSUE THREAD

**Issue by AdeYan0209** [sal0w/CC3200-Ultrasonic-sensor-HC-Sr04#1]
HI, when running the example I fount out that the LEDS (RGB) are blinking.
But when I review the code. I found nothing about Led pin define.
And when I want to modify the pulse from pin 64 to pin 21.
Nothing happen. Can you give me some indication about changing pin define.

BTW the code
MAP_GPIODirModeSet(GPIOA1_BASE, 0x2, GPIO_DIR_MODE_OUT);

what 0x2 mean , I have searched for a long time, but finding nothing.

**Comment by sal0w** [comment]
Hi ADEYEN,
**Change** - `MAP_GPIOPinWrite(GPIOA1_BASE, PIN_64,PIN_64);` -> `MAP_GPIOPinWrite(GPIOA1_BASE, PIN_64,2);`
**Change** - `MAP_GPIOPinWrite(GPIOA1_BASE,PIN_64,~PIN_64);` -> `MAP_GPIOPinWrite(GPIOA1_BASE, PIN_64, 0);
`

- This eliminates the LEDS blinking.

About pin definition and 0x2, I will try to answer by this weekend.

**Comment by sal0w** [comment]
I am closing this issue as of now.
